bug(source): fix "missing 1 required positional argument: 'resume_retries'"
To resolve resolve TB

```
    pip_downloader = Downloader(pip_session, "")
TypeError: Downloader.__init__() missing 1 required positional argument: 'resume_retries'
```

Signed-off-by: Ben Alkov <ben.alkov@redhat.com>